SCREEN_WIDTH = 600
SCREEN_HEIGHT = 800
TOP_BORDER = SCREEN_HEIGHT//2
RIGHT_BORDER = SCREEN_WIDTH//2
LEFT_BORDER = -RIGHT_BORDER
BOTTOM_BORDER = -TOP_BORDER

SMALL_FONT = ('Courier', 24, 'normal')
BIG_FONT = ('Courier', 30, 'normal')

BACKGROUND_COLOR = 'black'
OBJECT_COLOR = 'white'
