# Generated by Django 5.2.4 on 2025-07-21 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cafe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, unique=True)),
                ('map_url', models.URLField(max_length=500)),
                ('img_url', models.URLField(max_length=500)),
                ('location', models.CharField(max_length=250)),
                ('seats', models.CharField(max_length=250)),
                ('has_toilet', models.BooleanField()),
                ('has_wifi', models.BooleanField()),
                ('has_sockets', models.BooleanField()),
                ('can_take_calls', models.BooleanField()),
                ('coffee_price', models.CharField(blank=True, max_length=250, null=True)),
            ],
        ),
    ]
